### ISSUE TITLE
Check in form + admin statistics

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#188]
#### Description

I'm building out some functionality with a microservice atm to allow us to centralize hack night checkins, but we'd want to see about tying in a simple checkin form in brigadehub + an admin panel to review basic statistics: numbers over time, churn rate, etc. 

refer https://github.com/sfbrigade/Member-Support/issues/6 for context

This is most likely late-beta / pre-live functionality.
#### Screenshots

C4A checkin form:

![](https://i.imgur.com/os1UAaw.png)
#### Tasks
- [ ] New route/controller/view for public checkin form
- [ ] New route/controller/view for admin checkin form management
- [ ] New route/controller/view for admin statistics dashboard (should be pre-defined charts for first iteration)

**Comment by therebelrobot** [comment]
@davidhincapie, here's the issue where this was being tracked. Feel free to post your findings / wireframes / ideas here.
