### ISSUE TITLE
IE8 + Github Login is Failing

### ISSUE THREAD

**Issue by andrewmbacon** [therebelrobot/brigadehub#198]
#### Description
- Attempting to login, github says it does not support ie8, IE9
- After logging in, page displays error. 
#### Screenshots

![image](https://cloud.githubusercontent.com/assets/5542706/14516019/edab55ba-01b3-11e6-8a70-7f2a78ed1ebb.png)
![image](https://cloud.githubusercontent.com/assets/5542706/14516022/f0d83528-01b3-11e6-8905-57335c4a9198.png)

![image](https://cloud.githubusercontent.com/assets/5542706/14516527/c1cd10dc-01b8-11e6-8d41-11b4329778bd.png)
#### To Reproduce

Attempt to login from IE8/9
#### Tasks
- [ ] Confirm this fails on a real IE device, not just virtual box. 
- [ ] Consider dropping IE8/9 support for editing, only keeping it for viewing sites. 
- [ ] Investigate further why the login is failing.
