### ISSUE TITLE
Elevating authentication scope

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#221]
#### Description

A basic user or blogger may not want to provide all the same permissions in github as a superadmin (private repos, org admin, etc.) Should provide a method of elevating permissions as needed in application
##### User Role / scope breakdown

| role | scope |
| --- | --- |
| none | none |
| `read` | `user`,`public_repo` |
| `blog` | `user`,`public_repo` |
| `lead` | `user`, `repo` |
| `core`, `superAdmin` | `user`, `repo`, `admin:org`, `admin:repo_hook`, `admin:org_hook` |
#### Screenshots

![](https://i.imgur.com/2VYDjqG.png)
#### Files
- `config/passport.js:191-210`
- `app.js`
#### Tasks
- [ ] Add `checkScope` middleware function that consumes desired scopes on server start and checks user for scopes on authentication
- [ ] Add `elevateScope` controller function (next to `checkScope`) that sends you to github to request additional scopes
- [ ] Add `/auth/github/elevate` route that attaches to `elevateScope` controller
