### ISSUE TITLE
Migrate blog from Jekyll

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#227]
#### Description

SuperAdmin or Core roles need to be able to import blog posts from an existing Jekyll blog (like [sfbrigade.github.io](https://github.com/sfbrigade/sfbrigade.github.io))
#### Files
- `models/Posts.js`
- `themes/atl/views/blog/manage.js`
- `controllers/blog.js`
#### Tasks
- [ ] Interface with Github API
- [ ] Request all posts contained in the `_posts` directory
- [ ] Format data into Posts model, save to MongoDB

**Comment by therebelrobot** [comment]
This was delivered.
