### ISSUE TITLE
Add docker-compose file

### ISSUE THREAD

**Issue by rahulkgupta** [therebelrobot/brigadehub#293]
#### Description

The docker set up right now requires the developer to have mongodb installed natively. 
#### Screenshots

![Downhill Windmills](http://i.giphy.com/KO8AG2EByqkFi.gif)
#### Files
- https://github.com/sfbrigade/brigadehub/blob/develop/Dockerfile
#### Tasks
- [ ] Add docker-compose.yml file
  - [ ] Add image reference to mongodb
- [ ] Remove reference to mongo in the docker file. 
- [ ] Clean up port exposure

We should also remove the secrets from the Docker file but I imagine that's an extra level of effort.
