### ISSUE TITLE
Add breadcrumbs to all pages

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#296]
#### Description

should match the breadcrumbs in blog list and blog post
#### Screenshots

![](https://i.imgur.com/PG8LFDq.png)
#### Tasks
- [x] Events
- [x] Project list
- [x] individual project
- [x] contact/about
- [x] account management
- [x] edit blog post
- [x] manage blog posts
- [x] edit project
- [x] manage projects
- [x] new project
- [x] new blog post
- [x] manage events
- [x] edit/new event

**Comment by Juxtaposeidon** [comment]
added breadcrumbs to pages on list
