### ISSUE TITLE
SCM abstraction layer

### ISSUE THREAD

**Issue by howdoicomputer** [therebelrobot/brigadehub#44]
It would be great if brigades weren't tied down to a specific source control management solution with BrigadeHub. If a brigade wants to use hosted GitLab or any other 'bring your own scm' solution in contrast to GitHub then they should feel free to do so.

To that effect, I want to write an abstraction layer for our interactions with an scm platform.

Example: Associating a group or repository with a project requires contacting an scm platform endpoint; collecting repositories, groups, and their respective metadata; then creating the model associations between data sets (project -> group). 

I'll aggregate the related calls to GitLab/GitHub/Etc in one library to expose to my fellow contributors as a single point of entry for scm related actions.

**Potential scms:**
- GitHub (lol)
- GitLab hosted
- GitLab deployed
- Phrabricator

I won't target Phrabricator due to MVP but it should be kept in mind as a potential target. I really don't see it being picked up by a brigade, however.

@therebelrobot Let me know what kind of interaction with GitHub is planned/needed so I can limit scope.

**Initial feature set:**
- Authorization
- [Repositories](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/repos.js)
- [Users](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/user.js)
- [Issues](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/issues.js)
- [Organizations](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/orgs.js)

Anything outside of this feature set should be specified within a separate ticket.

**ToDo:**
- [ ] Internal API and usage documentation for wrapper library (stored in wiki)
- [ ] Test layout and code structure
- [ ] Possibly create a 'fake' GitLab instance for testing
- [ ] Enough of a code structure to make API calls
- [ ] Tests with cached responses from scm
- [ ] Actual code: Auth
- [ ] Actual code: Repos
- [ ] Actual code: Users
- [ ] Actual code: Issues
- [ ] Actual code: Orgs

**Resources:**
- https://www.npmjs.com/package/github
- https://www.npmjs.com/package/node-gitlab
- https://www.npmjs.com/package/sepia

**Comment by therebelrobot** [comment]
So the main pieces needed are pulling/managing user lists from organizations, pulling project data from repos in an org, possibly publishing back to those (the cms updated content content will be pulled/pushed to a dedicated content repo)

I'm sure there's something I'm missing, but that's the basic I can think of right now.

**Comment by therebelrobot** [comment]
Also, TIL SEPIA IS PROBABLY THE BEST THING EVER. Just saying.

**Comment by howdoicomputer** [comment]
That's what I figured and what I've started working on. Anything outside the initial delivery of those features should probably be filed into a separate ticket.

Yeah, I have used the Ruby library VCR a little bit with a [different project](https://github.com/howdoicomputer/junar) and for some company internal software.

**Comment by therebelrobot** [comment]
separate ticket: :+1: - Make sure to edit the OP and put in a list of features this will deliver, e.g. `- [ ] user lists` etc.

VCR: this is why we open source, folks. You find rad stuff like this because of rockstars like @howdoicomputer :D

**Comment by howdoicomputer** [comment]
@therebelrobot Too kind. I updated the original ticket.

**Comment by therebelrobot** [comment]
SCM at this stage isn't specifically needed, as any brigade that we've talked to used github. Will readress this if we run into another brigade that uses bitbucket/gitlab/etc.
