### ISSUE TITLE
3/2 Brigadehub Agenda

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#46]
taking a page from [Code for Boston's book](https://github.com/studentinsights/studentinsights/issues/135)
#### Review priorities
- current: Roadmap see #45. Given everyone is ok with what is in the roadmap, we'll need to see about:
  - [ ] Updating current issue list to reflect new roadmap milestones
  - [ ] Add any additional issues to get to `alpha`
- next: ramp up to be ready for codeacross and `alpha` milestone
- after: 
#### Finish what's in progress
- [ ] Design / logo, #29 
- [ ] Build out html/jade skeleton for alpha frontend
- [ ] Map out all the data structures we need to populate frontend
- [ ] SCM abstraction, #44 
#### Help new folks pitch in
- Talk about any questions from the roadmap
- Help them set up development environment
- Start with Help wanted issues
- Next, help with new pieces of current feature
- After, start with a new feature

cc @sfbrigade/project-brigadehub

**Comment by jszwedko** [comment]
:clap: I really like this
