### ISSUE TITLE
Alpha release features

### ISSUE THREAD

**Issue by jasonlally** [therebelrobot/brigadehub#51]
see https://github.com/sfbrigade/brigadehub/issues/45

All Alpha features should be listed under the [`ALPHA - v1.x.x`](https://github.com/sfbrigade/brigadehub/labels/ALPHA%20-%20v1.x.x) tag, and be listed in the [`v1.0.0 (Alpha Release)`](https://github.com/sfbrigade/brigadehub/milestones/v1.0.0%20%28Alpha%20Release%29) Milestone.
- [ ] Blog List page #113
  - [x] Dynamic population of list #91
  - [ ] Blog List Page Styling #95 
- [ ] Manage Blog List #115
  - [ ] Manage Blog List Page Styling #97 
- [ ] Single blog post page #92 #120
  - [ ] Individual Blog Page Styling #96 
- [ ] Single blog post page Admin Edit #89 #122
  - [ ] Edit Individual Blog Page Styling #94 
- [ ] Events page #56 
- [ ] Events page Admin Edit #127
- [ ] Projects page #128
- [ ] Projects page Admin Edit #110
- [ ] Single project page #132
- [ ] Single project page Admin Edit #134
- [ ] About / Contact #55
- [ ] About / Contact Admin Edit #138
- [ ] Landing / Home page #54
- [ ] Landing / Home page Admin Edit #136
- [ ] Login page
- [ ] Login page Admin Edit
- [ ] User List / Management #165 
- [ ] Account Management #112
- [ ] Brigade Management Admin Edit #119

Design will be mimicking [Code for Poland's new website](http://kodujdlapolski.pl/en/)

**_Any sub tasks for alpha should be listed in this page for reference**_

EDIT HISTORY:

_Edits by @therebelrobot, Friday Mar 4 2016, 11:27 am PT. For original post, see https://github.com/sfbrigade/brigadehub/issues/51#issuecomment-192430185_

_Edits by @therebelrobot, Sunday Mar 20 2016, 11:53 am PT. For previous post, see https://github.com/sfbrigade/brigadehub/issues/51#issuecomment-198987964_

**Comment by jasonlally** [comment]
Oh, also, as a related note, I would not consider the moving the existing design part of "feature parity," please feel free to go a different direction. I'm for any design that increases usability and also looks beautiful. I'll leave that to the experts ;-)

On that note, any improvements that can be made to content, design, layout, etc should be made to the extent possible during this alpha phase (understanding of course we don't want perfect to be the enemy of good). 

I think we want to avoid simply moving the furniture to a different house without taking the opportunity to do some redecorating and applying fresh coats of paint.

**Comment by therebelrobot** [comment]
> Oh, also, as a related note, I would not consider the moving the existing design part of "feature parity," please feel free to go a different direction. I'm for any design that increases usability and also looks beautiful. I'll leave that to the experts ;-)

Fair point. I think low hanging fruit would be to move over 1:1 the styling as well, but maybe we can try a different design, like the new [Code for Poland website](http://kodujdlapolski.pl/en/)? Simple, clean, modern, and focused on projects?

EDIT: I posed the idea of moving to the Poland design to the core team, and the overall feeling was positive. Let's shoot for this tomorrow.

**Comment by therebelrobot** [comment]
Also, I'm going to be retconning @jasonlally's original post to make sure we have a solid list of features to shoot for tomorrow, be aware.

**Comment by therebelrobot** [comment]
_original post by @jasonlally:_

Based on conversation with @therebelrobot, I wanted to take a stab at defining "feature parity" with the existing site in more detail, which is the goal of developing the alpha version of brigadehub per #45 

This is by no means **the** definition but I wanted to get something out there to help define alpha in a little more detail. I think the best way to do this is through some lightweight stories. So here it goes:
1. A visitor should be able to learn a little about what Code for San Francisco is and how it works
2. A visitor should be able to see projects being worked on (past and present) at the Brigade hack nights in a simple beautiful list
3. A visitor should be able to know when and where hack night is and how to RSVP
4. A visitor or brigade member should be able to find upcoming events
5. A visitor should be able to sign up for the newsletter and see past newsletters
6. A hack night attendee should be able to check in to hack night
7. A new member should have a simple entry point for learning the different ways they can get involved
8. A brigade member should be able to post stories or blog posts (see below though as I think we should maybe do an integration rather than a build here)

At a broader level, my hope for the platform is that it really helps accelerate/improve the following for the brigade (among other things, but I put these at the top of my list):
1. Provide a transparent way for anyone to understand what's happening on projects/code at the brigade
2. Provide simple ways for people to sort, filter and get connected to projects they find interesting
3. Provide ways for project leads to add/edit aspects about a project (leveraging other infrastructure like github and best practices wherever possible)
4. Provide simple, obvious ways to get connected to the Brigade organization and its infrastructure (signing up for slack, getting on the newsletter, etc.)

And an even larger point, I think we should challenge ourselves to only do serious builds where clear additional value is provided, but leverage integrations and APIs for other reasonable collaboration services (GitHub, Slack, Medium, etc.). Likely, more research and assumption testing would need to be done, but some other thoughts I've had:
1. Would it be better for blogging to leverage Medium and their APIs? https://github.com/Medium/medium-api-docs - they've already got editing down and it would be really easy to maintain a CfSF publication and add people as necessary. Also the discovery and syndication impacts increase.
2. Can we do more integration with Meetup so we can leverage the high discoverability on Meetup.com but make sure when folks find us on the site we don't completely take them out of the site? Maybe not and maybe it's not really a problem. Either way we should just make sure events show up without having to enter them in multiple places.

**Comment by therebelrobot** [comment]
@jasonlally the ideas outside of the feature list described at the top should probably be directed to the #45 Brigade Roadmap issue, I'll transfer your entire comment over for future reference.

**Comment by therebelrobot** [comment]
_EDIT HISTORY POST_

see https://github.com/sfbrigade/brigadehub/issues/45
- [ ] A working landing page #54
- [ ] A working about page #55
- [ ] A working events page #56
- [ ] A working blogging platform #57
- [ ] A working projects list #58
- [ ] User management for CMS functionality #3 

Design will be mimicking [Code for Poland's new website](http://kodujdlapolski.pl/en/) (#2). We'll be iterating on this more in the future, we just need to get something out there.

The additional ideas/direction below are possibilities for future iterations, but not specifically necessary for alpha release.

**Comment by therebelrobot** [comment]
Moving @davidcarvel's comment from the roadmap discussion over to here, since it's more pertinent to Alpha release in particular:

---

Posting image from last week's meeting on Alpha features. Will create issues for any that do not have them. Links go to the open tasks for that page.

**Alpha Features**
-Projects Page User: [https://github.com/sfbrigade/brigadehub/issues/128]
-Projects Page Admin: [https://github.com/sfbrigade/brigadehub/issues/110]
-Individual Projects Page User: [https://github.com/sfbrigade/brigadehub/issues/132]
-Individual Projects Page Admin: [https://github.com/sfbrigade/brigadehub/issues/134]
-Account Management (user only) [https://github.com/sfbrigade/brigadehub/issues/112]
-Blog Listing Page User: [https://github.com/sfbrigade/brigadehub/issues/113]
-Blog Listing Page Admin: [https://github.com/sfbrigade/brigadehub/issues/115]
-Brigade Management Page (admin only) [https://github.com/sfbrigade/brigadehub/issues/119]
-Individual Blog Page User: [https://github.com/sfbrigade/brigadehub/issues/120]
-Individual Blog Page Admin: [https://github.com/sfbrigade/brigadehub/issues/122]
-Events Page User: [https://github.com/sfbrigade/brigadehub/issues/56]
-Events Page Admin [https://github.com/sfbrigade/brigadehub/issues/127]
-About/Contact Us Page User: [https://github.com/sfbrigade/brigadehub/issues/55]
-About/Contact Us Page Admin: [https://github.com/sfbrigade/brigadehub/issues/138]
-Home/Landing Page User: [https://github.com/sfbrigade/brigadehub/issues/54]
-Home/Landing Page Admin: [https://github.com/sfbrigade/brigadehub/issues/136]

**Future/Beta/Live**
-Dynamic redirects [https://github.com/sfbrigade/brigadehub/issues/34]
-Accessibility [https://github.com/sfbrigade/brigadehub/issues/19]
-Individual pages for events [https://github.com/sfbrigade/brigadehub/issues/141] -- needs details
-Icons/assets [https://github.com/sfbrigade/brigadehub/issues/140] -- needs details
-Logo [https://github.com/sfbrigade/brigadehub/issues/29]
-Internationalization [https://github.com/sfbrigade/brigadehub/issues/146]

![bh whiteboard_16mar16](https://cloud.githubusercontent.com/assets/17933351/13978177/60e4a9de-f0a5-11e5-8fe8-917e5e81f209.jpg)
