### ISSUE TITLE
No documentation / workflow for changing DNS of a current installation

### ISSUE THREAD

**Issue by jacebrowning** [therebelrobot/brigadehub#510]
There is currently no easy-to-use way of changing a dns location for an already installed Brigadehub instance. The hard-to-use way, while works, is undocumented, and should at the very least be surfaced for discovery.

#### Tasks

- [ ] Document the current method of changing DNS of a previously installed instance
- [ ] Scope out a non-developer way of changing DNS (needs to be deployment-platform-agnostic)
- [ ] Implement non-developer workflow of changing DNS

_Note: This issue is not for discussion of issues with Github OAuth after dns change or after installation. Please refer to the [previously created core issue](https://github.com/brigadehub/core/issues/25) for further discussion on that topic_

Edited by @therebelrobot on 27Apr2017, after [this comment](https://github.com/brigadehub/brigadehub/issues/510#issuecomment-297771646) (for context)

---

> Original issue by @jacebrowning:

> Title: Support for custom domains?

#### Type

I think this could be a **docs update**.

#### Description

My apologies if this is documented somewhere, but I couldn't find it.

We have successfully deployed BrigadeHub to Heroku. We wanted to set up a custom domain (and also rename the Heroku app to something more unique).

Our app **WAS** was at http://citizen-labs.herokuapp.com, but is **NOW** a http://citizen-labs-hub.herokuapp.com with a custom domain of https://hub.citizenlabs.org.

When we try to login on the custom domain, it's still trying to use the old Heroku app domain and redirecting us to: http://citizen-labs.herokuapp.com/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

What is the correct way to move our deployment to a new domain? Thanks!

**Comment by pltaylor** [comment]
Chances are that you need to reconfigure your domain settings in the Heroku -> Settings page, under the Domains & certificates section.

**Comment by jacebrowning** [comment]
I believe that we have already made the necessary changes on the Heroku side:

<img width="958" alt="screen shot 2017-04-19 at 3 23 46 pm" src="https://cloud.githubusercontent.com/assets/939501/25198074/4a8b722c-2514-11e7-9f2b-b132e3dbf4f7.png">

**Comment by therebelrobot** [comment]
> I think this could be a docs update.

This is definitely a docs update. The initial launch of brigadehub was at http://codeforsanfrancisco.org.

Let me know if you're still having a problem, but if not, I'll get this lined up to document.

**Comment by pltaylor** [comment]
So I just checked https://hub.citizenlabs.org/ and from my connection it is loading what appears to be the same page as http://citizen-labs-hub.herokuapp.com/#  

Try it in incognito?

**Comment by therebelrobot** [comment]
Also verified from here in SF that https://hub.citizenlabs.org/ is loading brigadehub. You may need to flush your computer's DNS cache to see the new site.

**Comment by carlvlewis** [comment]
DNS is very picky with Heroku. You have to first get an SSL cert on Heroku
after adding the domain to your instance. Then you have to point the DNS
from your registrar using an ALIAS record (CNAME is possible but will screw
up all other subdomains and email). The registrar we had didn't allow ALIAS
records. We had to transfer to dnsimple. Then we pointed the ALIAS record
to 'yourappnamehere.herokudns.com' with wildcard '*'. Sorry if that sounds
confusing. Happy to explain more once back at computer.

**Comment by carlvlewis** [comment]
Also if you already have SSL with your registrar, you'll need to add ALIAS
records set to 'yourappname.herokussl.com'

**Comment by jacebrowning** [comment]
Let me clarify. When I go to https://hub.citizenlabs.org, I see our BrigadeHub, but when when I try to log in via GitHub, I am taken to  http://citizen-labs.herokuapp.com/auth/github/callback/... (our old Heroku domain).

**Comment by therebelrobot** [comment]
Ah, @jacebrowning that's a misconfiguration on the github side. In manage brigade in Brigadehub, make sure the homepage url listed is https://hub.citizenlabs.org, and in the oauth registration for the installation on Github, make sure the url's match as well.

**Comment by jacebrowning** [comment]
Therein lies the problem in that I can't log into our deployment without being sent to a non-existent https://citizen-labs.herokuapp.com.

It sounds like I need to try:

1. Rename https://citizen-labs-hub.herokuapp.com to https://citizen-labs.herokuapp.com
2. Log in to https://citizen-labs.herokuapp.com to set the homepage URL to https://hub.citizenlabs.org
3. Rename https://citizen-labs.herokuapp.com to https://citizen-labs-hub.herokuapp.com to match our DNS
4. Set up a new OAuth registration with GitHub for https://hub.citizenlabs.org

**Comment by pltaylor** [comment]
In Heroku open up the mongo access by clicking on the Resources->Mlab instance.  Then in the brigades object edit the "url" value to be your homepage and save it.  Once you do that it should be good to go.

**Comment by therebelrobot** [comment]
@jacebrowning, those steps sound accurate, with @pltaylor's mlab workaround. Let us know if you run into issues while doing that.

I'm not sure how we can go about streamlining the changing of the heroku instance name directly... due to security concerns, that is a tricky problem. Lemme do some exploration on that, and see what I can come up with.

**Comment by jacebrowning** [comment]
I have updated the "url" value via mLab. How do I revoke/renew the OAuth registration?

I have revoked access in on the organization settings:

 
<img width="755" alt="screen shot 2017-04-19 at 4 29 57 pm" src="https://cloud.githubusercontent.com/assets/939501/25200795/99090406-251d-11e7-804b-0e9c4ed6c77f.png">


but https://hub.citizenlabs.org/auth/github is still trying to access http://citizen-labs.herokuapp.com/.

**Comment by therebelrobot** [comment]
The user that registered would have to change it, unless it's attached to the org as a whole. If you registered it yourself, go to settings > oauth applications > click on the installation name and change the settings

**Comment by pltaylor** [comment]
@jacebrowning If you are still having problems w/ this you can DM me on CFA Slack channel and I'll do my best to get you straightened up.

**Comment by jacebrowning** [comment]
We're getting closer. We have deleted the OAuth application that was tied to a user's account and created a new application at our organization level:

<img width="769" alt="screen shot 2017-04-20 at 10 00 49 am" src="https://cloud.githubusercontent.com/assets/939501/25234638/b6ac95de-25b0-11e7-9952-4c65ea578630.png">

I also manually updated `["auth"]["github"]["clientId"]` and `["clientSecret"]` in the database to match the new keys, but were are now seeing this when logging in:

<img width="1112" alt="screen shot 2017-04-20 at 10 06 35 am" src="https://cloud.githubusercontent.com/assets/939501/25235018/e3da29a8-25b1-11e7-8fd8-8e553c76f935.png">

**Comment by pltaylor** [comment]
you need to add /callback.... i.e. http://opensavannah.org/auth/github/callback

**Comment by jacebrowning** [comment]
Hmm, same result:

<img width="702" alt="screen shot 2017-04-20 at 10 32 20 am" src="https://cloud.githubusercontent.com/assets/939501/25235985/b59e4166-25b4-11e7-8eb1-3c0c021cd0f7.png">

Do I need to clear a session somewhere?

**Comment by pltaylor** [comment]
No need to clear anything.

**Comment by pltaylor** [comment]
and what is the url in your mongo db?

**Comment by jacebrowning** [comment]
```
"github": "https://github.com/citizenlabsgr",
"url": "https://hub.citizenlabs.org",
"slug": "https://github.com/citizenlabsgr",
```

**Comment by pltaylor** [comment]
ok, do one thing for me.....take the s off of https in both your mongo instance and your oauth profile in github and try it.

**Comment by jacebrowning** [comment]
That worked!

**Comment by pltaylor** [comment]
I'm glad that worked....I'm also frustrated that it worked.  I do not know why that fixes it, which upsets me.

**Comment by jacebrowning** [comment]
Thanks for your help! Perhaps someone else will benefit from reading this thread in the future. 🎉

**Comment by therebelrobot** [comment]
The outstanding problems that were highlighted in this issue are twofold:

1. Github Auth fails when using https (being worked on in https://github.com/brigadehub/core/issues/25)
2. Documentation / workflow surrounding changing DNS of a current installation is lacking.

as the first is being worked on, I'll ask that discussion around that be moved to that previous issue on core.

As the second one does not yet have an issue to track it, I'll be renaming and reusing this issue to track work on it.
