### ISSUE TITLE
Epic: Landing page (public page)

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#54]
We need a landing page which shows the following:
- [ ] Name and basic info about the brigade
- [ ] Brigade logo/images 
- [ ] Way to join Slack channel
- [ ] Next Meetup event
- [ ] A small form to sign up for newsletter (should tie into user model, with a non-logged in fallback)
- [ ] A sampling of the projects
- [ ] A sampling of the blog posts
- [ ] Partner information
- [ ] A way to update this information via an edit page

Design should be based off [Code for Poland](http://kodujdlapolski.pl/en/)

**Comment by therebelrobot** [comment]
@ondrae, added slack signup to alpha list, as per [your comment](https://github.com/sfbrigade/brigadehub/issues/45#issuecomment-192469551)

**Comment by andrewmbacon** [comment]
Ok, basic layout for homepage completed. In "Landing" branch.

**Comment by therebelrobot** [comment]
LGTM @andrewmbacon. Now we need to tie in some controller logic for CMSing the content.
