### ISSUE TITLE
Epic: Contact/About (public page)

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#55]
We need a working About page with the following features:
- [x] Info about the leadership team (should default to user model data)
- [x] Contact info for leadership and brigade as a whole
- [x] A contact form to send an email to a generic contact email for the brigade
- [ ] a way to update this info via an edit page
- [ ] Styling [https://github.com/sfbrigade/brigadehub/issues/139]

Design should be based off http://kodujdlapolski.pl/en/contact/

**Comment by Juxtaposeidon** [comment]
i can take a look at the about page by wed. would the way to update the info be through the 'manage users' page since we're looking at user data, or are we looking at something separate?

**Comment by therebelrobot** [comment]
> would the way to update the info be through the 'manage users' page since we're looking at user data

yepyep. For any user with the `core` or higher role. We'll also want to put the option to opt out of displaying contact info

**Comment by therebelrobot** [comment]
That being said, there should probably still be a separate Edit About Page, where the admin can specify order of users, set other contextual text, etc.
