### ISSUE TITLE
Epic: Events list (public page)

### ISSUE THREAD

**Issue by therebelrobot** [therebelrobot/brigadehub#56]
We need a landing page for future events, with a calendar and list of upcoming events and how to RSVP/attend
- [x] Calendar with events shown [https://github.com/sfbrigade/brigadehub/issues/123]
- [x] list of events below the calendar if JS isn't available
- [x] integration with Meetup API to pull current events #6 
- [x] a way to subscribe to events or show interest [https://github.com/sfbrigade/brigadehub/issues/124]

Design should follow the basic design principles of the other pages (Code for Poland relies on Facebook for events), so we'll be pulling elements from Google calendar's month view, as well as facebook's event list:

![](https://i.imgur.com/nbgHH3M.png)
