### ISSUE TITLE
CSS styling for blog related pages

### ISSUE THREAD

**Issue by howdoicomputer** [therebelrobot/brigadehub#77]
- [ ] Blog edit page _styling_ (⌐■_■) #94 
- [ ] Blog list page _styling_ (⌐■_■) #95 
- [ ] Blog list manage page _styling_ (⌐■_■) #97 
- [ ] Blog display page _styling_ (⌐■_■) #96 

The blog edit page isn't the best and I'm pretty bad at making things look pretty via CSS. Would be pretty grateful if someone poked around here and made helped with the layout of the from group.

Update: I made this ticket more granular and removed its `subticket` status in favor of the `Section: Blog` tag.

**Comment by therebelrobot** [comment]
> The blog list page is filled with static, stubbed out content at the moment. It would be nice if the list page was populated via blog documents taken from MongoDB.

Yes, absolutely.

> The blog edit page is pretty bad and I'm pretty bad at making things look pretty via CSS. Would be pretty grateful if someone poked around here and made helped with the layout of the from group.

I can take a look at the CSS for that, or @spiffysparrow / @andrewmbacon can take a crack at it if either of them have time.

> There is an express-messages library that helps with generating flashes. That can be pulled in as well.

We already have a flash message system in place in the application, [`express-flash`](https://www.npmjs.com/package/express-flash), and it's being used across the board for various actions, like user signup and profile updating. You can find an example of it [here](https://github.com/sfbrigade/brigadehub/blob/edge/controllers/user.js#L47). Let me know if you have any trouble with it, it seems feature-complete enough for most of our use cases, though I could be wrong.

**Comment by howdoicomputer** [comment]
@therebelrobot Ah, that was the library that I google'd. Forgot that the code base had every library under the sun.

**Comment by howdoicomputer** [comment]
The flash messages were a side effect of the parent task and handled in [this PR](https://github.com/sfbrigade/brigadehub/pull/87).

**Comment by therebelrobot** [comment]
This should probably be split out to three separate issues: Styling for Blog list page, Styling for individual blog page, and styling for edit blog post page. Will create additional issues and tag here.

**Comment by therebelrobot** [comment]
I've added links to the individual tasks for those sections. Closing this in favor of those.
