### ISSUE TITLE
Epic: Individual Blog Post (management)

### ISSUE THREAD

**Issue by howdoicomputer** [therebelrobot/brigadehub#89]
- [ ] Pull specific blog document from Mongo
- [ ] Post and update document
- [ ] Flash messages to inform the user that the post is updated
- [ ] Page redirect

This may be blocked on ISSUE-#77 since it'll be hard for a user to sort and retrieve a blog post and being able to look at a grid of published posts and subsequently clicking on one would be a better UX.

That being said, you can create an edit page by seeding a blog document through `/blog/new` or creating it manually in Mongo itself.

It may be a good idea to copy/inherit the code from `/blog/new` for `/blog/edit`... just need to figure out how to shove the `plaintextcontent` field into `simplemde` (the markdown editor we're using) and then POST it.

**Comment by howdoicomputer** [comment]
There is a `/blog/manage` route. FYI.

So maybe have the same vertical list or grid from the `/blogs` route but if you click on one of the links then it takes you to a `/blogs/edit` page that is a copy of `/blogs/new` but with the content of the the simplemde editor populated with the blog content.

**Comment by therebelrobot** [comment]
> There is a /blog/manage route. FYI.

Correct. There are currently 10 blog related routes, as following: 
- `GET /blog` - Public facing: the Blog Listing
- `GET /blog/manage` - Admin facing: managing the list of blog posts, can trigger sync or bulk operations
- `GET /blog/new` - Admin facing: add new blog post
- `GET /blog/:blogId` - Public facing: an individual blog post
- `GET /blog/:blogId/edit` - Admin facing: update blog post

Each `GET` route will have its own view associated with it. Additionally, there are `POST` routes for most of the above, to allow for admin administration. These should respond with a flash message and redirect:
- `POST /blog/manage` - Admin facing: bulk operations
- `POST /blog/sync` - Admin facing: sync blog list from external source (wordpress, github, whatever)
- `POST /blog/new` - Admin facing: save new blog post
- `POST /blog/:blogId` - Admin facing: save updates to individual blog post
- `POST /blog/:blogId/sync` - Admin facing: sync an individual post from source (wordpress, github, w/e)
